apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogni-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogni-back
  template:
    metadata:
      labels:
        app: dogni-back
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: dogni-back
          image: ghcr.io/jacob0418/dogni_back:latest
          ports:
            - containerPort: 3000
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: dogni-secrets
                  key: mongo_url
